---
# handlers file for ansible-role-cerebro
- name: Restart Cerebro service Centos/RedHat 7 and Amazon
  systemd:
    name: cerebro
    daemon_reload: yes
    state: restarted
    enabled: yes
  listen: Restart Cerebro